argocd:
  namespace: argocd
  project: default

source:
  repoURL: https://github.com/Stagecraft-Ops/stagecraft-helm.git
  targetRevision: main

destination:
  server: https://kubernetes.default.svc
  namespace: stagecraft

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

services:
  - name: stagecraft-api
    path: charts/stagecraft-api
    valuesFiles:
      - values.yaml
      - values.dev.yaml
  - name: stagecraft-webhook
    path: charts/stagecraft-webhook
    valuesFiles:
      - values.yaml
      - values.dev.yaml
  - name: stagecraft-worker
    path: charts/stagecraft-worker
    valuesFiles:
      - values.yaml
      - values.dev.yaml
  - name: stagecraft-frontend
    path: charts/stagecraft-frontend
    valuesFiles:
      - values.yaml
      - values.dev.yaml
