argocd:
  namespace: argocd
  project: default

source:
  repoURL: https://github.com/aGora-Ops/agora-helm.git
  targetRevision: main

destination:
  server: https://kubernetes.default.svc
  namespace: agora

syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

services:
  - name: agora-api
    path: charts/agora-api
    valuesFiles:
      - values.yaml
      - values.dev.yaml
  - name: agora-webhook
    path: charts/agora-webhook
    valuesFiles:
      - values.yaml
      - values.dev.yaml
  - name: agora-worker
    path: charts/agora-worker
    valuesFiles:
      - values.yaml
      - values.dev.yaml
  - name: agora-frontend
    path: charts/agora-frontend
    valuesFiles:
      - values.yaml
      - values.dev.yaml
