image:
  repository: "591316257673.dkr.ecr.us-east-1.amazonaws.com/stagecraft-frontend"
  tag: "develop-3f24bf58"
environment: dev
env:
  NEXTAUTH_URL: "https://ustbiteshub.online"
externalSecrets:
  secretsManagerPath: stagecraft/dev/frontend
