{{- if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "agora-api.fullname" . }}
  namespace: agora
  labels:
    {{- include "agora-api.labels" . | nindent 4 }}
rules: []
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agora-api.fullname" . }}
  namespace: agora
  labels:
    {{- include "agora-api.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: agora
roleRef:
  kind: Role
  name: {{ include "agora-api.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
