image:
  repository: "686566045205.dkr.ecr.us-east-1.amazonaws.com/stagecraft-webhook"
  tag: "develop-4aeb087c"

replicaCount: 1

autoscaling:
  enabled: false

environment: dev

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

externalSecrets:
  secretsManagerPath: stagecraft/dev/webhook
