image:
  repository: "591316257673.dkr.ecr.us-east-1.amazonaws.com/stagecraft-webhook"
  tag: "develop-6257911d"
environment: dev
externalSecrets:
  secretsManagerPath: stagecraft/dev/webhook

aws:
  mainAccountId: "591316257673"
  clusterName: "stagecraft-dev"
