image:
  repository: ""
  tag: "develop-017fc9fd"

replicaCount: 1

autoscaling:
  enabled: false

environment: dev

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 1000m
    memory: 1Gi

externalSecrets:
  secretsManagerPath: stagecraft/dev/worker
