image:
  repository: ""
  tag: "develop-1b190e0d"

replicaCount: 1

environment: dev

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

externalSecrets:
  secretsManagerPath: stagecraft/dev/mcp-github
