{{- if .Values.externalSecrets.secretsManagerPath }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "stagecraft-frontend.fullname" . }}-secrets
  namespace: stagecraft
  labels:
    {{- include "stagecraft-frontend.labels" . | nindent 4 }}
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore
  target:
    name: {{ include "stagecraft-frontend.fullname" . }}-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.externalSecrets.secretsManagerPath }}
{{- end }}
